/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TaskType = IDL.Variant({
  'exercise' : IDL.Null,
  'sleep' : IDL.Null,
  'mindfulness' : IDL.Null,
  'hydration' : IDL.Null,
  'nutrition' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Nat,
  'difficulty' : IDL.Nat,
  'createdAt' : IDL.Nat,
  'rewardPoints' : IDL.Nat,
  'description' : IDL.Text,
  'taskType' : TaskType,
});
export const QuestLog = IDL.Record({
  'completedQuests' : IDL.Vec(Task),
  'dailyQuests' : IDL.Vec(Task),
  'lastGenerated' : IDL.Nat,
  'failedQuests' : IDL.Vec(Task),
});
export const PhysicalCapabilities = IDL.Record({
  'balance' : IDL.Nat,
  'flexibility' : IDL.Nat,
  'strength' : IDL.Nat,
  'endurance' : IDL.Nat,
});
export const Preferences = IDL.Record({
  'timeAvailability' : IDL.Nat,
  'difficultyPreference' : IDL.Nat,
  'exerciseTypes' : IDL.Vec(IDL.Text),
});
export const Habits = IDL.Record({
  'activityLevel' : IDL.Nat,
  'sleepQuality' : IDL.Nat,
  'dietQuality' : IDL.Nat,
  'smoking' : IDL.Bool,
  'alcoholConsumption' : IDL.Nat,
});
export const HealthConditions = IDL.Record({
  'heartConditions' : IDL.Bool,
  'respiratoryIssues' : IDL.Bool,
  'jointIssues' : IDL.Bool,
  'diabetes' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'completedTasks' : IDL.Nat,
  'capabilities' : PhysicalCapabilities,
  'currentTasks' : IDL.Vec(Task),
  'level' : IDL.Nat,
  'preferences' : Preferences,
  'experience' : IDL.Nat,
  'habits' : Habits,
  'conditions' : HealthConditions,
});

export const idlService = IDL.Service({
  'addHabitToProfile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'completeExercise' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'completeHydration' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'completeMindfulness' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'completeNutrition' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'completeSleep' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'deleteHabitFromProfile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'getQuestLog' : IDL.Func([IDL.Text], [IDL.Opt(QuestLog)], ['query']),
  'getSuggestionsByQuestId' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], []),
  'getTasks' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'updateUserProfile' : IDL.Func([IDL.Text, UserProfile], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TaskType = IDL.Variant({
    'exercise' : IDL.Null,
    'sleep' : IDL.Null,
    'mindfulness' : IDL.Null,
    'hydration' : IDL.Null,
    'nutrition' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Nat,
    'difficulty' : IDL.Nat,
    'createdAt' : IDL.Nat,
    'rewardPoints' : IDL.Nat,
    'description' : IDL.Text,
    'taskType' : TaskType,
  });
  const QuestLog = IDL.Record({
    'completedQuests' : IDL.Vec(Task),
    'dailyQuests' : IDL.Vec(Task),
    'lastGenerated' : IDL.Nat,
    'failedQuests' : IDL.Vec(Task),
  });
  const PhysicalCapabilities = IDL.Record({
    'balance' : IDL.Nat,
    'flexibility' : IDL.Nat,
    'strength' : IDL.Nat,
    'endurance' : IDL.Nat,
  });
  const Preferences = IDL.Record({
    'timeAvailability' : IDL.Nat,
    'difficultyPreference' : IDL.Nat,
    'exerciseTypes' : IDL.Vec(IDL.Text),
  });
  const Habits = IDL.Record({
    'activityLevel' : IDL.Nat,
    'sleepQuality' : IDL.Nat,
    'dietQuality' : IDL.Nat,
    'smoking' : IDL.Bool,
    'alcoholConsumption' : IDL.Nat,
  });
  const HealthConditions = IDL.Record({
    'heartConditions' : IDL.Bool,
    'respiratoryIssues' : IDL.Bool,
    'jointIssues' : IDL.Bool,
    'diabetes' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'completedTasks' : IDL.Nat,
    'capabilities' : PhysicalCapabilities,
    'currentTasks' : IDL.Vec(Task),
    'level' : IDL.Nat,
    'preferences' : Preferences,
    'experience' : IDL.Nat,
    'habits' : Habits,
    'conditions' : HealthConditions,
  });
  
  return IDL.Service({
    'addHabitToProfile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'completeExercise' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'completeHydration' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'completeMindfulness' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'completeNutrition' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'completeSleep' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'deleteHabitFromProfile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'getQuestLog' : IDL.Func([IDL.Text], [IDL.Opt(QuestLog)], ['query']),
    'getSuggestionsByQuestId' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], []),
    'getTasks' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'updateUserProfile' : IDL.Func([IDL.Text, UserProfile], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };