/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Habits {
  'activityLevel' : bigint,
  'sleepQuality' : bigint,
  'dietQuality' : bigint,
  'smoking' : boolean,
  'alcoholConsumption' : bigint,
}
export interface HealthConditions {
  'heartConditions' : boolean,
  'respiratoryIssues' : boolean,
  'jointIssues' : boolean,
  'diabetes' : boolean,
}
export interface PhysicalCapabilities {
  'balance' : bigint,
  'flexibility' : bigint,
  'strength' : bigint,
  'endurance' : bigint,
}
export interface Preferences {
  'timeAvailability' : bigint,
  'difficultyPreference' : bigint,
  'exerciseTypes' : Array<string>,
}
export interface QuestLog {
  'completedQuests' : Array<Task>,
  'dailyQuests' : Array<Task>,
  'lastGenerated' : bigint,
  'failedQuests' : Array<Task>,
}
export interface Task {
  'id' : bigint,
  'duration' : bigint,
  'difficulty' : bigint,
  'createdAt' : bigint,
  'rewardPoints' : bigint,
  'description' : string,
  'taskType' : TaskType,
}
export type TaskType = { 'exercise' : null } |
  { 'sleep' : null } |
  { 'mindfulness' : null } |
  { 'hydration' : null } |
  { 'nutrition' : null };
export interface UserProfile {
  'completedTasks' : bigint,
  'capabilities' : PhysicalCapabilities,
  'currentTasks' : Array<Task>,
  'level' : bigint,
  'preferences' : Preferences,
  'experience' : bigint,
  'habits' : Habits,
  'conditions' : HealthConditions,
}
export interface _SERVICE {
  'addHabitToProfile' : ActorMethod<[string, string], boolean>,
  'completeExercise' : ActorMethod<[bigint, bigint], boolean>,
  'completeHydration' : ActorMethod<[bigint, bigint], boolean>,
  'completeMindfulness' : ActorMethod<[bigint, bigint], boolean>,
  'completeNutrition' : ActorMethod<[bigint, bigint], boolean>,
  'completeSleep' : ActorMethod<[bigint, bigint], boolean>,
  'deleteHabitFromProfile' : ActorMethod<[string, string], boolean>,
  'getQuestLog' : ActorMethod<[string], [] | [QuestLog]>,
  'getSuggestionsByQuestId' : ActorMethod<[bigint], Array<string>>,
  'getTasks' : ActorMethod<[string], Array<Task>>,
  'getUserProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'updateUserProfile' : ActorMethod<[string, UserProfile], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];