/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PhysicalCapabilities {
    balance: bigint;
    flexibility: bigint;
    strength: bigint;
    endurance: bigint;
}
export interface QuestLog {
    completedQuests: Array<Task>;
    dailyQuests: Array<Task>;
    lastGenerated: bigint;
    failedQuests: Array<Task>;
}
export interface Habits {
    activityLevel: bigint;
    sleepQuality: bigint;
    dietQuality: bigint;
    smoking: boolean;
    alcoholConsumption: bigint;
}
export interface Preferences {
    timeAvailability: bigint;
    difficultyPreference: bigint;
    exerciseTypes: Array<string>;
}
export interface Task {
    id: bigint;
    duration: bigint;
    difficulty: bigint;
    createdAt: bigint;
    rewardPoints: bigint;
    description: string;
    taskType: TaskType;
}
export interface HealthConditions {
    heartConditions: boolean;
    respiratoryIssues: boolean;
    jointIssues: boolean;
    diabetes: boolean;
}
export interface UserProfile {
    completedTasks: bigint;
    capabilities: PhysicalCapabilities;
    currentTasks: Array<Task>;
    level: bigint;
    preferences: Preferences;
    experience: bigint;
    habits: Habits;
    conditions: HealthConditions;
}
export enum TaskType {
    exercise = "exercise",
    sleep = "sleep",
    mindfulness = "mindfulness",
    hydration = "hydration",
    nutrition = "nutrition"
}
export interface backendInterface {
    addHabitToProfile(habit: string, userId: string): Promise<boolean>;
    completeExercise(exerciseId: bigint, repetitions: bigint): Promise<boolean>;
    completeHydration(taskId: bigint, _timestamp: bigint): Promise<boolean>;
    completeMindfulness(taskId: bigint, _timestamp: bigint): Promise<boolean>;
    completeNutrition(taskId: bigint, _timestamp: bigint): Promise<boolean>;
    completeSleep(taskId: bigint, _timestamp: bigint): Promise<boolean>;
    deleteHabitFromProfile(habit: string, userId: string): Promise<boolean>;
    getQuestLog(userId: string): Promise<QuestLog | null>;
    getSuggestionsByQuestId(questId: bigint): Promise<Array<string>>;
    getTasks(userId: string): Promise<Array<Task>>;
    getUserProfile(userId: string): Promise<UserProfile | null>;
    updateUserProfile(userId: string, profile: UserProfile): Promise<boolean>;
}
import type { Habits as _Habits, HealthConditions as _HealthConditions, PhysicalCapabilities as _PhysicalCapabilities, Preferences as _Preferences, QuestLog as _QuestLog, Task as _Task, TaskType as _TaskType, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addHabitToProfile(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addHabitToProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHabitToProfile(arg0, arg1);
            return result;
        }
    }
    async completeExercise(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completeExercise(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeExercise(arg0, arg1);
            return result;
        }
    }
    async completeHydration(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completeHydration(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeHydration(arg0, arg1);
            return result;
        }
    }
    async completeMindfulness(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completeMindfulness(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeMindfulness(arg0, arg1);
            return result;
        }
    }
    async completeNutrition(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completeNutrition(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeNutrition(arg0, arg1);
            return result;
        }
    }
    async completeSleep(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completeSleep(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeSleep(arg0, arg1);
            return result;
        }
    }
    async deleteHabitFromProfile(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHabitFromProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHabitFromProfile(arg0, arg1);
            return result;
        }
    }
    async getQuestLog(arg0: string): Promise<QuestLog | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestLog(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestLog(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSuggestionsByQuestId(arg0: bigint): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuggestionsByQuestId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuggestionsByQuestId(arg0);
            return result;
        }
    }
    async getTasks(arg0: string): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserProfile(arg0: string, arg1: UserProfile): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0, to_candid_UserProfile_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0, to_candid_UserProfile_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_QuestLog_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestLog): QuestLog {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_TaskType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskType): TaskType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuestLog]): QuestLog | null {
    return value.length === 0 ? null : from_candid_QuestLog_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedTasks: bigint;
    capabilities: _PhysicalCapabilities;
    currentTasks: Array<_Task>;
    level: bigint;
    preferences: _Preferences;
    experience: bigint;
    habits: _Habits;
    conditions: _HealthConditions;
}): {
    completedTasks: bigint;
    capabilities: PhysicalCapabilities;
    currentTasks: Array<Task>;
    level: bigint;
    preferences: Preferences;
    experience: bigint;
    habits: Habits;
    conditions: HealthConditions;
} {
    return {
        completedTasks: value.completedTasks,
        capabilities: value.capabilities,
        currentTasks: from_candid_vec_n4(_uploadFile, _downloadFile, value.currentTasks),
        level: value.level,
        preferences: value.preferences,
        experience: value.experience,
        habits: value.habits,
        conditions: value.conditions
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedQuests: Array<_Task>;
    dailyQuests: Array<_Task>;
    lastGenerated: bigint;
    failedQuests: Array<_Task>;
}): {
    completedQuests: Array<Task>;
    dailyQuests: Array<Task>;
    lastGenerated: bigint;
    failedQuests: Array<Task>;
} {
    return {
        completedQuests: from_candid_vec_n4(_uploadFile, _downloadFile, value.completedQuests),
        dailyQuests: from_candid_vec_n4(_uploadFile, _downloadFile, value.dailyQuests),
        lastGenerated: value.lastGenerated,
        failedQuests: from_candid_vec_n4(_uploadFile, _downloadFile, value.failedQuests)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    duration: bigint;
    difficulty: bigint;
    createdAt: bigint;
    rewardPoints: bigint;
    description: string;
    taskType: _TaskType;
}): {
    id: bigint;
    duration: bigint;
    difficulty: bigint;
    createdAt: bigint;
    rewardPoints: bigint;
    description: string;
    taskType: TaskType;
} {
    return {
        id: value.id,
        duration: value.duration,
        difficulty: value.difficulty,
        createdAt: value.createdAt,
        rewardPoints: value.rewardPoints,
        description: value.description,
        taskType: from_candid_TaskType_n7(_uploadFile, _downloadFile, value.taskType)
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    exercise: null;
} | {
    sleep: null;
} | {
    mindfulness: null;
} | {
    hydration: null;
} | {
    nutrition: null;
}): TaskType {
    return "exercise" in value ? TaskType.exercise : "sleep" in value ? TaskType.sleep : "mindfulness" in value ? TaskType.mindfulness : "hydration" in value ? TaskType.hydration : "nutrition" in value ? TaskType.nutrition : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n5(_uploadFile, _downloadFile, x));
}
function to_candid_TaskType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskType): _TaskType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_Task_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Task): _Task {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedTasks: bigint;
    capabilities: PhysicalCapabilities;
    currentTasks: Array<Task>;
    level: bigint;
    preferences: Preferences;
    experience: bigint;
    habits: Habits;
    conditions: HealthConditions;
}): {
    completedTasks: bigint;
    capabilities: _PhysicalCapabilities;
    currentTasks: Array<_Task>;
    level: bigint;
    preferences: _Preferences;
    experience: bigint;
    habits: _Habits;
    conditions: _HealthConditions;
} {
    return {
        completedTasks: value.completedTasks,
        capabilities: value.capabilities,
        currentTasks: to_candid_vec_n14(_uploadFile, _downloadFile, value.currentTasks),
        level: value.level,
        preferences: value.preferences,
        experience: value.experience,
        habits: value.habits,
        conditions: value.conditions
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    duration: bigint;
    difficulty: bigint;
    createdAt: bigint;
    rewardPoints: bigint;
    description: string;
    taskType: TaskType;
}): {
    id: bigint;
    duration: bigint;
    difficulty: bigint;
    createdAt: bigint;
    rewardPoints: bigint;
    description: string;
    taskType: _TaskType;
} {
    return {
        id: value.id,
        duration: value.duration,
        difficulty: value.difficulty,
        createdAt: value.createdAt,
        rewardPoints: value.rewardPoints,
        description: value.description,
        taskType: to_candid_TaskType_n17(_uploadFile, _downloadFile, value.taskType)
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskType): {
    exercise: null;
} | {
    sleep: null;
} | {
    mindfulness: null;
} | {
    hydration: null;
} | {
    nutrition: null;
} {
    return value == TaskType.exercise ? {
        exercise: null
    } : value == TaskType.sleep ? {
        sleep: null
    } : value == TaskType.mindfulness ? {
        mindfulness: null
    } : value == TaskType.hydration ? {
        hydration: null
    } : value == TaskType.nutrition ? {
        nutrition: null
    } : value;
}
function to_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Task>): Array<_Task> {
    return value.map((x)=>to_candid_Task_n15(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
